namespace Client.Main.Controls.UI.Game.Hud
{
    /// <summary>
    /// Mobile bottom HUD layout (HP/MP crystals, potion slots, EXP bar, and SD/AG bars).
    /// Coordinates use the default virtual UI space; Y is measured from the screen bottom
    /// so the HUD remains stable across resolutions. Values are exported from the editor.
    /// </summary>
    public static class BottomBarLayout
    {
        // Generated by the hud-edit-bottombar layout editor.
        public static float CrystalW = 82f;
        public static float CrystalH = 75f;
        public static float CrystalBottom = 3f;
        public static float CrystalGap = 5f;
        public static float ClawNudge = -2f;
        // Vertical claw adjustment (+ moves down; 0 attaches it to the crystal base).
        public static float ClawOffsetY = 8f;
        // Absolute claw size in pixels; editable in the layout editor.
        public static float ClawW = 94f;
        public static float ClawH = 53f;
        public static float CrystalNumFont = 12f;

        public static int SlotCount = 5;
        public static float SlotSize = 42f;
        public static float SlotGap = 3f;
        public static float SlotsBottom = 10f;

        public static bool ExpEnabled = true;
        public static float ExpH = 8f;
        public static float ExpBottom = 0f;
        public static float ExpW = 0f;

        public static bool PlateEnabled = true;
        public static float PlateInset = 0f;
        public static float PlateTopPad = 4f;

        public static bool SideBarsEnabled = true;
        public static float SideBarH = 29f;
        public static float SideBarW = 128f;
        public static float SideBarOverlap = 10f;
        public static float SideBarBottom = 52f;
        public static float SideBarLeftX = -14f;
        public static float SideBarRightX = 14f;

        public static float SideBarLeftFill = 1f;
        public static float SideBarRightFill = 1f;
        public static float SideBarFillOffsetL = -1.6f;
        public static float SideBarFillOffsetR = 0f;
        public static bool SideBarFillFromHeadL = false;
        public static bool SideBarFillFromHeadR = true;
        // Trough positions measured from the artwork export. The values keep both sides
        // visually balanced after mirroring.
        public static float SideBarTroughL = 0.14f;
        public static float SideBarTroughR = 0.69f;
        public static float SideBarTroughRL = 0.32f;
        public static float SideBarTroughRR = 0.86f;
        public static float SideBarTroughTop = 0.27f;
        public static float SideBarTroughBottom = 0.88f;
        public static bool SideBarTextEnabled = true;
        public static float SideBarTextFont = 10f;
        public static float SideBarTextOffsetY = 0f;
        public static float SideBarTextOffsetX = 0f;
        public static float SideBarTextLeftX = -12f;
        public static float SideBarTextRightX = 12f;
        public static float SideBarTextShadow = 1f;
        public static string SideBarTextLeftOverride = "69 / 69";
        public static string SideBarTextRightOverride = "24 / 24";

        public static bool SideBarFadeEnabled = true;
        public static bool FadeSnapToTrough = true;
        // Fade trough limits measured from the artwork. The same 12/41 and 36/41
        // constants are used on both sides.
        public static float FadeTroughTop = 12f / 41f;
        public static float FadeTroughBottom = 36f / 41f;

        public static bool FadeAOn = true;
        public static float FadeAW = 0f, FadeAH = 0.6f, FadeAX = 13f, FadeAY = 0f;
        public static bool FadeAFlip = false;

        public static bool FadeBOn = true;
        public static float FadeBW = 0f, FadeBH = 0.6f, FadeBX = 36f, FadeBY = 0f;
        public static bool FadeBFlip = false;

        public static bool FadeCOn = true;
        public static float FadeCW = 0f, FadeCH = 0.6f, FadeCX = 36f, FadeCY = 0f;
        public static bool FadeCFlip = false;

        public static bool FadeDOn = true;
        public static float FadeDW = 0f, FadeDH = 0.6f, FadeDX = 13f, FadeDY = 0f;
        public static bool FadeDFlip = false;

        public static bool OverlayLEnabled = true;
        public static float OverlayLW = 128f, OverlayLH = 4f, OverlayLX = 3f, OverlayLBottom = 49f;
        public static bool OverlayLFlip = true;

        public static bool OverlayREnabled = true;
        public static float OverlayRW = 128f, OverlayRH = 4f, OverlayRX = -3f, OverlayRBottom = 49f;
        public static bool OverlayRFlip = true;

        public static bool LevelTextEnabled = true;
        public static float LevelTextX = 10f;
        public static float LevelTextBottom = 6f;
        public static float LevelFont = 10.5f;
        public static float ExpTextFont = 8.5f;
    }
}
